services:
  postgres:
    image: postgres:latest
    container_name: ondeal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ondeal
      POSTGRES_USER: ondeal
      POSTGRES_PASSWORD: ondeal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
    driver: local

